# Site settings
title: Piotr Lasek
email: piotr.lasek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piotrlasek.com" # the base hostname & protocol for your site
twitter_username: pp_lasek
github_username:  piotrlasek

# Build settings
markdown: kramdown

paginate: 10
